# Generated by Django 6.0 on 2025-12-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_in_inventory', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_quantity', models.PositiveIntegerField(default=5)),
                ('measurements', models.CharField(blank=True, max_length=200, null=True)),
                ('price_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
